# Generated by Django 5.2.5 on 2025-08-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('summary', models.TextField(max_length=200, verbose_name='Summary')),
                ('degree', models.CharField(max_length=200, verbose_name='Degree')),
                ('school', models.CharField(max_length=200, verbose_name='School')),
                ('university', models.CharField(max_length=200, verbose_name='University')),
                ('previous_work', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Previous Work Experience')),
                ('skills', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Skills')),
            ],
        ),
    ]
